In [ ]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('bomojobrandindices.csv')

In [ ]:
df

   Brand\tTotal\tReleases\t#1 Release\tLifetime Gross
0   Marvel Comics\t15806336901\t69\tAvengers: Endg...
1   Legendary Pictures\t7018798067\t56\tJurassic W...
2   Lucasfilm\t6325022918\t39\tStar Wars: Episode ...
3     Pixar\t6078217662\t28\tIncredibles 2\t608581744
4   DC Comics\t5815645953\t46\tThe Dark Knight\t53...
5   DreamWorks Animation\t5792217737\t41\tShrek 2\...
6   Vertigo Entertainment\t3154664176\t41\tIt\t327...
7   Bad Robot\t3077078931\t15\tStar Wars: Episode ...
8   Walt Disney Animation Studios\t2774912904\t15\...
9   Illumination Entertainment\t2759505881\t13\tTh...
10  Blumhouse Productions\t2451844676\t49\tGet Out...
11  Hasbro\t2079485824\t17\tTransformers: Revenge ...
12  Nickelodeon\t1930746182\t26\tTeenage Mutant Ni...
13  Sony Pictures Animation\t1918763863\t21\tSpide...
14  Walden Media\t1842852183\t38\tThe Chronicles o...
15  Blue Sky\t1740428763\t13\tIce Age 3: Dawn of t...
16        Stephen King\t1729648950\t49\tIt\t327481748
17   MTV\t1520456359\t36\tThe Longest Yard\t158119460
18  Platinum Dunes\t1422911399\t19\tTeenage Mutant...
19  Saturday Night Live - Alumni Debuts\t102359603...
20   Dark Horse Comics\t947671338\t16\t300\t210614939
21  Tim Burton-Johnny Depp\t889955830\t8\tAlice in...
22  Warner Animation Group\t786497181\t8\tThe Lego...
23  Tyler Perry\t765635362\t16\tMadea Goes to Jail...
24  CBS Films\t652824187\t29\tScary Stories to Tel...
25   John Grisham\t645661825\t10\tThe Firm\t158348367
26  Robert Ludlum\t645459186\t6\tThe Bourne Ultima...
27    MonsterVerse\t580145113\t4\tGodzilla\t200676069
28  Hanna-Barbera\t578586146\t10\tScooby-Doo\t1532...
29  Nicholas Sparks\t574728259\t11\tThe Notebook\t...
30  Philip K. Dick\t495237720\t14\tMinority Report...
31      Dark Castle\t454625110\t16\tUnknown\t63686397
32  National Lampoon\t436669213\t21\tNational Lamp...
33  Disney Channel\t359952780\t8\tHigh School Musi...
34  Roald Dahl\t356238494\t7\tCharlie and the Choc...
35  Saturday Night Live\t346533876\t11\tWayne's Wo...
36  DisneyToon Studios\t337576791\t8\tPlanes\t9028...
37     Aardman\t333777829\t16\tChicken Run\t106834564
38            Laika\t300158323\t6\tCoraline\t75286229
39      Alan Moore\t276088604\t4\tWatchmen\t107509799
40  Amazon Studios\t204376048\t43\tManchester by t...
41    Clive Barker\t171686009\t10\tCandyman\t61186570
42        Disneynature\t151620585\t8\tEarth\t32011576
43  Broken Lizard\t73338237\t5\tSuper Troopers 2\t...
44  Studio Ghibli\t70666453\t26\tThe Secret World ...

In [ ]:
print(df.isnull().sum)

<bound method DataFrame.sum of     Brand\tTotal\tReleases\t#1 Release\tLifetime Gross
0                                               False
1                                               False
2                                               False
3                                               False
4                                               False
5                                               False
6                                               False
7                                               False
8                                               False
9                                               False
10                                              False
11                                              False
12                                              False
13                                              False
14                                              False
15                                              False
16                                              False
17                                              False
18                                              False
19                                              False
20                                              False
21                                              False
22                                              False
23                                              False
24                                              False
25                                              False
26                                              False
27                                              False
28                                              False
29                                              False
30                                              False
31                                              False
32                                              False
33                                              False
34                                              False
35                                              False
36                                              False
37                                              False
38                                              False
39                                              False
40                                              False
41                                              False
42                                              False
43                                              False
44                                              False >

In [ ]:
df.head()

  Brand\tTotal\tReleases\t#1 Release\tLifetime Gross
0  Marvel Comics\t15806336901\t69\tAvengers: Endg...
1  Legendary Pictures\t7018798067\t56\tJurassic W...
2  Lucasfilm\t6325022918\t39\tStar Wars: Episode ...
3    Pixar\t6078217662\t28\tIncredibles 2\t608581744
4  DC Comics\t5815645953\t46\tThe Dark Knight\t53...

In [ ]:
df.describe()

       Brand\tTotal\tReleases\t#1 Release\tLifetime Gross
count                                                  45
unique                                                 45
top     Marvel Comics\t15806336901\t69\tAvengers: Endg...
freq                                                    1

In [ ]:
df.shape

(45, 1)

In [ ]:
display(df.describe(include="all"))

       Brand\tTotal\tReleases\t#1 Release\tLifetime Gross
count                                                  45
unique                                                 45
top     Marvel Comics\t15806336901\t69\tAvengers: Endg...
freq                                                    1